# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Configure oh-my-zsh
export ZSH=$HOME/.oh-my-zsh

## Use powerlevel10k theme
ZSH_THEME="powerlevel10k/powerlevel10k"

## Use hyphen-insensitive completion.
HYPHEN_INSENSITIVE="true"

## Update automatically without asking
zstyle ':omz:update' mode auto

## Add plugins
plugins=(git)
plugins+=(zsh-vi-mode)

# Source configurations
source $ZSH/oh-my-zsh.sh
source ~/.p10k.zsh

# Environment
EDITOR="vim"
VISUAL="vim"

# Setup PATH
if [ "$(command -v go)" ]; then
  export PATH=$PATH:$(go env GOPATH)/bin
fi

# Configure rbenv
if [ "$(command -v rbenv)" ]; then
  eval "$(rbenv init -)"
fi

# Configure copilot CLI
if [ "$(command -v github-copilot-cli)" ]; then
  eval "$(github-copilot-cli alias -- "$0")"
fi
